
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-logistics
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./docker-volume/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./docker-volume/mosquitto/data:/mosquitto/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - bankingnet

networks:
  bankingnet:
    external: true

