lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)PerSec, topic=(.+)><>Count"
    name: "kafka_server_$1_$2_per_sec"
    labels:
      topic: "$3"
    type: COUNTER

  - pattern: "kafka.server<type=(.+), name=(.+), topic=(.+)><>Value"
    name: "kafka_server_$1_$2"
    labels:
      topic: "$3"
    type: GAUGE

  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: "kafka_server_$1_$2"
    type: GAUGE

  - pattern: "kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value"
    name: "kafka_log_$1"
    labels:
      topic: "$2"
      partition: "$3"
    type: GAUGE

  - pattern: "kafka.network<type=(.+), name=(.+)><>Value"
    name: "kafka_network_$1_$2"
    type: GAUGE

  - pattern: "kafka.controller<type=(.+), name=(.+)><>Value"
    name: "kafka_controller_$1_$2"
    type: GAUGE

  - pattern: "java.lang<type=Memory><>HeapMemoryUsage"
    name: "jvm_memory_heap"
    type: GAUGE

  - pattern: "java.lang<type=GarbageCollector, name=(.+)><>CollectionCount"
    name: "jvm_gc_collection_count"
    labels:
      gc: "$1"
    type: COUNTER

